# Generated by Django 4.1.7 on 2025-04-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
